version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:1.25.3
    restart: always
    ports:
      - "8082:8080"  # Changed host port to avoid conflict
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'text2vec-transformers'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://transformers:8080'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    depends_on:
      - transformers

  transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-all-mpnet-base-v2
    restart: always
    ports:
      - "8081:8080"  # This is fine unless another process uses 8081

volumes:
  weaviate_data:
